insert into team (id, name, gold, silver, bronze, total) values (1,'United States',41,23,28,92);
insert into team (id, name, gold, silver, bronze, total) values (2,'China',31,26,24,81);
insert into team (id, name, gold, silver, bronze, total) values (3,'Russia',20,23,20,63);
insert into team (id, name, gold, silver, bronze, total) values (4,'Great Britain',18,16,17,51);
insert into team (id, name, gold, silver, bronze, total) values (5,'Germany',16,16,18,50);
insert into team (id, name, gold, silver, bronze, total) values (6,'Australia',16,13,13,42);
insert into team (id, name, gold, silver, bronze, total) values (7,'Japan',14,10,14,38);
insert into team (id, name, gold, silver, bronze, total) values (8,'France',12,17,18,47);
insert into team (id, name, gold, silver, bronze, total) values (9,'Korea',10,5,10,25);
insert into team (id, name, gold, silver, bronze, total) values (10,'Brazil',8,9,3,20);
insert into team (id, name, gold, silver, bronze, total) values (11,'Kenya',8,5,3,16);
insert into team (id, name, gold, silver, bronze, total) values (12,'New Zealand',7,11,7,25);
insert into team (id, name, gold, silver, bronze, total) values (13,'Netherlands',7,9,10,26);
insert into team (id, name, gold, silver, bronze, total) values (14,'Cuba',7,5,4,16);
insert into team (id, name, gold, silver, bronze, total) values (15,'Poland',6,5,2,13);
insert into team (id, name, gold, silver, bronze, total) values (16,'Ukraine',6,4,13,23);
insert into team (id, name, gold, silver, bronze, total) values (17,'Hungary',6,3,10,19);
insert into team (id, name, gold, silver, bronze, total) values (18,'Spain',6,3,5,14);
insert into team (id, name, gold, silver, bronze, total) values (19,'Italy',6,2,10,18);
insert into team (id, name, gold, silver, bronze, total) values (20,'Kazakhstan',4,4,11,19);
insert into team (id, name, gold, silver, bronze, total) values (21,'Czech Republic',4,3,3,10);
insert into team (id, name, gold, silver, bronze, total) values (22,'Canada',3,8,5,16);
insert into team (id, name, gold, silver, bronze, total) values (23,'Iran',3,4,6,13);
insert into team (id, name, gold, silver, bronze, total) values (24,'Jamaica',3,4,4,11);
insert into team (id, name, gold, silver, bronze, total) values (25,'Serbia',3,4,1,8);
insert into team (id, name, gold, silver, bronze, total) values (26,'Croatia',3,3,2,8);
insert into team (id, name, gold, silver, bronze, total) values (27,'Turkey',3,2,5,10);
insert into team (id, name, gold, silver, bronze, total) values (28,'DPR Korea',3,1,4,8);
insert into team (id, name, gold, silver, bronze, total) values (29,'Colombia',3,1,0,4);
insert into team (id, name, gold, silver, bronze, total) values (30,'Slovenia',3,0,2,5);
insert into team (id, name, gold, silver, bronze, total) values (31,'Azerbaijan',2,4,10,16);
insert into team (id, name, gold, silver, bronze, total) values (32,'Mongolia',2,4,4,10);
insert into team (id, name, gold, silver, bronze, total) values (33,'Ethiopia',2,4,1,7);
insert into team (id, name, gold, silver, bronze, total) values (34,'Chinese Taipei',2,1,1,4);
insert into team (id, name, gold, silver, bronze, total) values (35,'Slovakia',2,0,3,5);
insert into team (id, name, gold, silver, bronze, total) values (36,'Denmark',1,6,3,10);
insert into team (id, name, gold, silver, bronze, total) values (37,'Uzbekistan',1,4,3,8);
insert into team (id, name, gold, silver, bronze, total) values (38,'Sweden',1,3,1,5);
insert into team (id, name, gold, silver, bronze, total) values (39,'Georgia',1,2,4,7);
insert into team (id, name, gold, silver, bronze, total) values (40,'Ireland',1,2,1,4);
insert into team (id, name, gold, silver, bronze, total) values (41,'Lithuania',1,2,1,4);
insert into team (id, name, gold, silver, bronze, total) values (42,'Armenia',1,2,0,3);
insert into team (id, name, gold, silver, bronze, total) values (43,'India',1,1,3,5);
insert into team (id, name, gold, silver, bronze, total) values (44,'Switzerland',1,1,3,5);
insert into team (id, name, gold, silver, bronze, total) values (45,'Austria',1,1,0,2);
insert into team (id, name, gold, silver, bronze, total) values (46,'Norway',1,1,0,2);
insert into team (id, name, gold, silver, bronze, total) values (47,'Argentina',1,0,1,2);
insert into team (id, name, gold, silver, bronze, total) values (48,'Eritrea',1,0,0,1);
insert into team (id, name, gold, silver, bronze, total) values (49,'Fiji',1,0,0,1);
insert into team (id, name, gold, silver, bronze, total) values (50,'Kosovo',1,0,0,1);
insert into team (id, name, gold, silver, bronze, total) values (51,'Qatar',1,0,0,1);
insert into team (id, name, gold, silver, bronze, total) values (52,'South Africa',0,6,3,9);
insert into team (id, name, gold, silver, bronze, total) values (53,'Thailand',0,4,3,7);
insert into team (id, name, gold, silver, bronze, total) values (54,'Belarus',0,4,2,6);
insert into team (id, name, gold, silver, bronze, total) values (55,'Romania',0,2,4,6);
insert into team (id, name, gold, silver, bronze, total) values (56,'Bahamas',0,2,1,3);
insert into team (id, name, gold, silver, bronze, total) values (57,'Belgium',0,1,3,4);
insert into team (id, name, gold, silver, bronze, total) values (58,'Finland',0,1,2,3);
insert into team (id, name, gold, silver, bronze, total) values (59,'Greece',0,1,2,3);
insert into team (id, name, gold, silver, bronze, total) values (60,'Bulgaria',0,1,1,2);
insert into team (id, name, gold, silver, bronze, total) values (61,'Moldova',0,1,1,2);
insert into team (id, name, gold, silver, bronze, total) values (62,'Morocco',0,1,1,2);
insert into team (id, name, gold, silver, bronze, total) values (63,'Bahrain',0,1,0,1);
insert into team (id, name, gold, silver, bronze, total) values (64,'Botswana',0,1,0,1);
insert into team (id, name, gold, silver, bronze, total) values (65,'Indonesia',0,1,0,1);
insert into team (id, name, gold, silver, bronze, total) values (66,'Malaysia',0,1,0,1);
insert into team (id, name, gold, silver, bronze, total) values (67,'Panama',0,1,0,1);
insert into team (id, name, gold, silver, bronze, total) values (68,'Latvia',0,0,3,3);
insert into team (id, name, gold, silver, bronze, total) values (69,'Egypt',0,0,2,2);
insert into team (id, name, gold, silver, bronze, total) values (70,'Mexico',0,0,2,2);
insert into team (id, name, gold, silver, bronze, total) values (71,'Tunisia',0,0,2,2);
insert into team (id, name, gold, silver, bronze, total) values (72,'Algeria',0,0,1,1);
insert into team (id, name, gold, silver, bronze, total) values (73,'Bosnia & Herzegovina',0,0,1,1);
insert into team (id, name, gold, silver, bronze, total) values (74,'Burundi',0,0,1,1);
insert into team (id, name, gold, silver, bronze, total) values (75,'Estonia',0,0,1,1);
insert into team (id, name, gold, silver, bronze, total) values (76,'Gabon',0,0,1,1);
insert into team (id, name, gold, silver, bronze, total) values (77,'Grenada',0,0,1,1);
insert into team (id, name, gold, silver, bronze, total) values (78,'Israel',0,0,1,1);
insert into team (id, name, gold, silver, bronze, total) values (79,'Ivory Coast',0,0,1,1);
insert into team (id, name, gold, silver, bronze, total) values (80,'Kyrgyzstan',0,0,1,1);
insert into team (id, name, gold, silver, bronze, total) values (81,'Nigeria',0,0,1,1);
insert into team (id, name, gold, silver, bronze, total) values (82,'Philippines',0,0,1,1);
insert into team (id, name, gold, silver, bronze, total) values (83,'Portugal',0,0,1,1);
insert into team (id, name, gold, silver, bronze, total) values (84,'Tajikistan',0,0,1,1);
insert into team (id, name, gold, silver, bronze, total) values (85,'Trinidad & Tobago',0,0,1,1);
insert into team (id, name, gold, silver, bronze, total) values (86,'Uganda',0,0,1,1);
insert into team (id, name, gold, silver, bronze, total) values (87,'Venezuela',0,0,1,1);
insert into team (id, name, gold, silver, bronze, total) values (88,'Vietnam',0,0,1,1);
