insert into team (name, gold, silver, bronze, total) values ('United States',41,23,28,92);
insert into team (name, gold, silver, bronze, total) values ('China',31,26,24,81);
insert into team (name, gold, silver, bronze, total) values ('Russia',20,23,20,63);
insert into team (name, gold, silver, bronze, total) values ('Great Britain',18,16,17,51);
insert into team (name, gold, silver, bronze, total) values ('Germany',16,16,18,50);
insert into team (name, gold, silver, bronze, total) values ('Australia',16,13,13,42);
insert into team (name, gold, silver, bronze, total) values ('Japan',14,10,14,38);
insert into team (name, gold, silver, bronze, total) values ('France',12,17,18,47);
insert into team (name, gold, silver, bronze, total) values ('Korea',10,5,10,25);
insert into team (name, gold, silver, bronze, total) values ('Brazil',8,9,3,20);
insert into team (name, gold, silver, bronze, total) values ('Kenya',8,5,3,16);
insert into team (name, gold, silver, bronze, total) values ('New Zealand',7,11,7,25);
insert into team (name, gold, silver, bronze, total) values ('Netherlands',7,9,10,26);
insert into team (name, gold, silver, bronze, total) values ('Cuba',7,5,4,16);
insert into team (name, gold, silver, bronze, total) values ('Poland',6,5,2,13);
insert into team (name, gold, silver, bronze, total) values ('Ukraine',6,4,13,23);
insert into team (name, gold, silver, bronze, total) values ('Hungary',6,3,10,19);
insert into team (name, gold, silver, bronze, total) values ('Spain',6,3,5,14);
insert into team (name, gold, silver, bronze, total) values ('Italy',6,2,10,18);
insert into team (name, gold, silver, bronze, total) values ('Kazakhstan',4,4,11,19);
insert into team (name, gold, silver, bronze, total) values ('Czech Republic',4,3,3,10);
insert into team (name, gold, silver, bronze, total) values ('Canada',3,8,5,16);
insert into team (name, gold, silver, bronze, total) values ('Iran',3,4,6,13);
insert into team (name, gold, silver, bronze, total) values ('Jamaica',3,4,4,11);
insert into team (name, gold, silver, bronze, total) values ('Serbia',3,4,1,8);
insert into team (name, gold, silver, bronze, total) values ('Croatia',3,3,2,8);
insert into team (name, gold, silver, bronze, total) values ('Turkey',3,2,5,10);
insert into team (name, gold, silver, bronze, total) values ('DPR Korea',3,1,4,8);
insert into team (name, gold, silver, bronze, total) values ('Colombia',3,1,0,4);
insert into team (name, gold, silver, bronze, total) values ('Slovenia',3,0,2,5);
insert into team (name, gold, silver, bronze, total) values ('Azerbaijan',2,4,10,16);
insert into team (name, gold, silver, bronze, total) values ('Mongolia',2,4,4,10);
insert into team (name, gold, silver, bronze, total) values ('Ethiopia',2,4,1,7);
insert into team (name, gold, silver, bronze, total) values ('Chinese Taipei',2,1,1,4);
insert into team (name, gold, silver, bronze, total) values ('Slovakia',2,0,3,5);
insert into team (name, gold, silver, bronze, total) values ('Denmark',1,6,3,10);
insert into team (name, gold, silver, bronze, total) values ('Uzbekistan',1,4,3,8);
insert into team (name, gold, silver, bronze, total) values ('Sweden',1,3,1,5);
insert into team (name, gold, silver, bronze, total) values ('Georgia',1,2,4,7);
insert into team (name, gold, silver, bronze, total) values ('Ireland',1,2,1,4);
insert into team (name, gold, silver, bronze, total) values ('Lithuania',1,2,1,4);
insert into team (name, gold, silver, bronze, total) values ('Armenia',1,2,0,3);
insert into team (name, gold, silver, bronze, total) values ('India',1,1,3,5);
insert into team (name, gold, silver, bronze, total) values ('Switzerland',1,1,3,5);
insert into team (name, gold, silver, bronze, total) values ('Austria',1,1,0,2);
insert into team (name, gold, silver, bronze, total) values ('Norway',1,1,0,2);
insert into team (name, gold, silver, bronze, total) values ('Argentina',1,0,1,2);
insert into team (name, gold, silver, bronze, total) values ('Eritrea',1,0,0,1);
insert into team (name, gold, silver, bronze, total) values ('Fiji',1,0,0,1);
insert into team (name, gold, silver, bronze, total) values ('Kosovo',1,0,0,1);
insert into team (name, gold, silver, bronze, total) values ('Qatar',1,0,0,1);
insert into team (name, gold, silver, bronze, total) values ('South Africa',0,6,3,9);
insert into team (name, gold, silver, bronze, total) values ('Thailand',0,4,3,7);
insert into team (name, gold, silver, bronze, total) values ('Belarus',0,4,2,6);
insert into team (name, gold, silver, bronze, total) values ('Romania',0,2,4,6);
insert into team (name, gold, silver, bronze, total) values ('Bahamas',0,2,1,3);
insert into team (name, gold, silver, bronze, total) values ('Belgium',0,1,3,4);
insert into team (name, gold, silver, bronze, total) values ('Finland',0,1,2,3);
insert into team (name, gold, silver, bronze, total) values ('Greece',0,1,2,3);
insert into team (name, gold, silver, bronze, total) values ('Bulgaria',0,1,1,2);
insert into team (name, gold, silver, bronze, total) values ('Moldova',0,1,1,2);
insert into team (name, gold, silver, bronze, total) values ('Morocco',0,1,1,2);
insert into team (name, gold, silver, bronze, total) values ('Bahrain',0,1,0,1);
insert into team (name, gold, silver, bronze, total) values ('Botswana',0,1,0,1);
insert into team (name, gold, silver, bronze, total) values ('Indonesia',0,1,0,1);
insert into team (name, gold, silver, bronze, total) values ('Malaysia',0,1,0,1);
insert into team (name, gold, silver, bronze, total) values ('Panama',0,1,0,1);
insert into team (name, gold, silver, bronze, total) values ('Latvia',0,0,3,3);
insert into team (name, gold, silver, bronze, total) values ('Egypt',0,0,2,2);
insert into team (name, gold, silver, bronze, total) values ('Mexico',0,0,2,2);
insert into team (name, gold, silver, bronze, total) values ('Tunisia',0,0,2,2);
insert into team (name, gold, silver, bronze, total) values ('Algeria',0,0,1,1);
insert into team (name, gold, silver, bronze, total) values ('Bosnia & Herzegovina',0,0,1,1);
insert into team (name, gold, silver, bronze, total) values ('Burundi',0,0,1,1);
insert into team (name, gold, silver, bronze, total) values ('Estonia',0,0,1,1);
insert into team (name, gold, silver, bronze, total) values ('Gabon',0,0,1,1);
insert into team (name, gold, silver, bronze, total) values ('Grenada',0,0,1,1);
insert into team (name, gold, silver, bronze, total) values ('Israel',0,0,1,1);
insert into team (name, gold, silver, bronze, total) values ('Ivory Coast',0,0,1,1);
insert into team (name, gold, silver, bronze, total) values ('Kyrgyzstan',0,0,1,1);
insert into team (name, gold, silver, bronze, total) values ('Nigeria',0,0,1,1);
insert into team (name, gold, silver, bronze, total) values ('Philippines',0,0,1,1);
insert into team (name, gold, silver, bronze, total) values ('Portugal',0,0,1,1);
insert into team (name, gold, silver, bronze, total) values ('Tajikistan',0,0,1,1);
insert into team (name, gold, silver, bronze, total) values ('Trinidad & Tobago',0,0,1,1);
insert into team (name, gold, silver, bronze, total) values ('Uganda',0,0,1,1);
insert into team (name, gold, silver, bronze, total) values ('Venezuela',0,0,1,1);
insert into team (name, gold, silver, bronze, total) values ('Vietnam',0,0,1,1);
